#!/bin/bash
#
# One-time build script: compiles LiteRT-LM C API into a shared library
#
# Uses Bazel to build from source. Run this ONCE, then Flutter's build
# system will bundle the resulting .so / .dylib automatically.
#
# Prerequisites: bazelisk/bazel 7.6.1+, clang, python3, git
#
# Usage:
#   ./build_litert_lm_dll.sh [/path/to/LiteRT-LM]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LITERT_LM_DIR="${1:-}"

echo ""
echo "============================================"
echo "  LiteRT-LM C API Shared Library Builder"
echo "============================================"
echo ""

# ============================================================================
# Resolve LiteRT-LM source directory
# ============================================================================

if [ -z "$LITERT_LM_DIR" ]; then
    for candidate in \
        "$PLUGIN_ROOT/../LiteRT-LM-ref" \
        "$PLUGIN_ROOT/../LiteRT-LM" \
        "$HOME/LiteRT-LM"; do
        if [ -f "$candidate/c/engine.h" ]; then
            LITERT_LM_DIR="$(cd "$candidate" && pwd)"
            break
        fi
    done
fi

if [ -z "$LITERT_LM_DIR" ] || [ ! -f "$LITERT_LM_DIR/c/engine.h" ]; then
    echo "ERROR: LiteRT-LM source not found." >&2
    echo "Pass the path as argument or clone to ../LiteRT-LM-ref" >&2
    echo "  git clone https://github.com/google-ai-edge/LiteRT-LM.git ../LiteRT-LM-ref" >&2
    exit 1
fi

# Detect platform and set output directory
OS=$(uname -s)
ARCH=$(uname -m)

case "$OS" in
    Darwin)
        if [ "$ARCH" = "arm64" ]; then
            NATIVE_ARCH="macos_arm64"
            LIB_EXT="dylib"
        else
            echo "ERROR: Only Apple Silicon (arm64) is supported for macOS" >&2
            exit 1
        fi
        ;;
    Linux)
        LIB_EXT="so"
        if [ "$ARCH" = "x86_64" ]; then
            NATIVE_ARCH="linux_x86_64"
        elif [ "$ARCH" = "aarch64" ]; then
            NATIVE_ARCH="linux_arm64"
        else
            echo "ERROR: Unsupported architecture: $ARCH" >&2
            exit 1
        fi
        ;;
    *)
        echo "ERROR: Unsupported OS: $OS (use build_litert_lm_dll.ps1 for Windows)" >&2
        exit 1
        ;;
esac

OUTPUT_DIR="$SCRIPT_DIR/prebuilt/$NATIVE_ARCH"
mkdir -p "$OUTPUT_DIR"

echo "LiteRT-LM source: $LITERT_LM_DIR"
echo "Platform:          $OS $ARCH ($NATIVE_ARCH)"
echo "Output dir:        $OUTPUT_DIR"
echo ""

# ============================================================================
# Verify tools
# ============================================================================

echo "Checking build tools..."

BAZEL=""
for cmd in bazelisk bazel; do
    if command -v "$cmd" &>/dev/null; then
        BAZEL="$cmd"
        echo "  Bazel: $(command -v $cmd)"
        break
    fi
done

if [ -z "$BAZEL" ]; then
    echo "ERROR: bazelisk or bazel not found in PATH" >&2
    exit 1
fi

echo ""

# ============================================================================
# Create temporary shared library target
# ============================================================================

echo "Setting up build target..."

BUILD_FILE="$LITERT_LM_DIR/c/BUILD"
STUB_FILE="$LITERT_LM_DIR/c/capi_dll_entry.cc"
BUILD_BACKUP="$BUILD_FILE.flutter_gemma_backup"

# Backup original BUILD file
cp "$BUILD_FILE" "$BUILD_BACKUP"

# Create stub source file
cat > "$STUB_FILE" << 'EOF'
// LiteRT-LM C API shared library entry point.
// All C API symbols are defined in engine.cc and exported via
// __attribute__((visibility("default"))) / __declspec(dllexport).
// This file exists only because Bazel cc_binary requires at least one source.
EOF

# Append shared library target to BUILD file
cat >> "$BUILD_FILE" << 'EOF'

# ======================================================================
# Flutter Gemma: Shared library target for Dart FFI
# (auto-generated by build_litert_lm_dll.sh — DO NOT COMMIT)
# ======================================================================
cc_binary(
    name = "litert_lm_capi",
    srcs = ["capi_dll_entry.cc"],
    linkshared = True,
    deps = [":engine"],
    visibility = ["//visibility:public"],
)
EOF

echo "  Created cc_binary(linkshared=True) target: //c:litert_lm_capi"
echo ""

# ============================================================================
# Cleanup function (runs on exit, even on error)
# ============================================================================

cleanup() {
    echo ""
    echo "Cleaning up temporary build files..."
    if [ -f "$BUILD_BACKUP" ]; then
        cp "$BUILD_BACKUP" "$BUILD_FILE"
        rm -f "$BUILD_BACKUP"
        echo "  Restored original c/BUILD"
    fi
    if [ -f "$STUB_FILE" ]; then
        rm -f "$STUB_FILE"
        echo "  Removed capi_dll_entry.cc"
    fi
}
trap cleanup EXIT

# ============================================================================
# Build with Bazel
# ============================================================================

echo "Building LiteRT-LM C API shared library..."
echo "  This may take a while on first build (downloads deps, compiles everything)"
echo ""

cd "$LITERT_LM_DIR"

# Build command differs slightly per platform
BAZEL_CONFIG=""
if [ "$OS" = "Darwin" ]; then
    BAZEL_CONFIG=""  # macOS uses default config
else
    BAZEL_CONFIG=""  # Linux uses default config
fi

$BAZEL build //c:litert_lm_capi $BAZEL_CONFIG

echo ""
echo "Build succeeded!"

# ============================================================================
# Copy output to our prebuilt directory
# ============================================================================

echo ""
echo "Copying build output..."

# Find the shared library in bazel-bin
DLL_PATH=""
for candidate in \
    "$LITERT_LM_DIR/bazel-bin/c/litert_lm_capi.$LIB_EXT" \
    "$LITERT_LM_DIR/bazel-bin/c/liblitert_lm_capi.$LIB_EXT" \
    "$LITERT_LM_DIR/bazel-bin/c/litert_lm_capi"; do
    if [ -f "$candidate" ]; then
        DLL_PATH="$candidate"
        break
    fi
done

if [ -n "$DLL_PATH" ]; then
    # Determine the correct output name
    if [ "$OS" = "Darwin" ]; then
        OUT_NAME="liblitert_lm_capi.dylib"
    else
        OUT_NAME="liblitert_lm_capi.so"
    fi

    cp "$DLL_PATH" "$OUTPUT_DIR/$OUT_NAME"
    size=$(du -h "$OUTPUT_DIR/$OUT_NAME" | cut -f1)
    echo "  Copied: $OUT_NAME ($size)"

    # Sign on macOS
    if [ "$OS" = "Darwin" ]; then
        codesign --force --sign - "$OUTPUT_DIR/$OUT_NAME" 2>/dev/null || true
        echo "  Signed: $OUT_NAME"
    fi
else
    echo "  WARNING: Shared library not found in bazel-bin/c/" >&2
    echo "  Listing bazel-bin/c/ contents:" >&2
    ls -la "$LITERT_LM_DIR/bazel-bin/c/" 2>/dev/null || true
fi

# Copy prebuilt accelerator libraries
PREBUILT_DIR="$LITERT_LM_DIR/prebuilt/$NATIVE_ARCH"
if [ -d "$PREBUILT_DIR" ]; then
    for lib in "$PREBUILT_DIR"/*.$LIB_EXT "$PREBUILT_DIR"/*.so; do
        [ -f "$lib" ] || continue
        filename=$(basename "$lib")
        cp "$lib" "$OUTPUT_DIR/$filename"
        echo "  Copied: $filename (accelerator)"
        # Sign on macOS
        if [ "$OS" = "Darwin" ]; then
            codesign --force --sign - "$OUTPUT_DIR/$filename" 2>/dev/null || true
        fi
    done
fi

# ============================================================================
# Summary
# ============================================================================

echo ""
echo "============================================"
echo "  Build complete!"
echo "============================================"
echo ""
echo "Output directory: $OUTPUT_DIR"
echo ""
echo "Contents:"
for f in "$OUTPUT_DIR"/*; do
    [ -f "$f" ] || continue
    size=$(du -h "$f" | cut -f1)
    echo "  $(basename "$f") ($size)"
done
echo ""
echo "Next: run 'flutter build' — the plugin will bundle these automatically."
